[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''
elseif self.config.type == 'play' or self.config.type == 'shop' or self.config.type == 'consumeable' then
card.states.drag.can = false
'''
position = "at"
payload = '''
elseif self.config.type == 'play' or self.config.type == 'shop' or self.config.type == 'consumeable' then
    if (self.config.type == 'shop' or self.config.type == 'consumeable') and G.SETTINGS.enable_dragging then 
        card.states.drag.can = true
    else
        card.states.drag.can = false
    end
'''
match_indent = true
