[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
G.hand.T.x = G.TILE_W - G.hand.T.w - 2.85
G.hand.T.y = G.TILE_H - G.hand.T.h
'''
position = "at"
payload = '''
G.hand.T.x = G.TILE_W - G.hand.T.w - 2.85 + ((SilkTouch.OS == 'Android' or SilkTouch.OS == 'iOS') and G.widescreen and -0.6 or 0)
G.hand.T.y = G.TILE_H - G.hand.T.h
G.hand.T.w = G.hand.T.w + ((SilkTouch.OS == 'Android' or SilkTouch.OS == 'iOS') and G.widescreen and 0.7 or 0)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
G.play.T.y = G.hand.T.y - 3.6
'''
position = "after"
payload = '''
G.play.T.w = G.play.T.w + ((SilkTouch.OS == 'Android' or SilkTouch.OS == 'iOS') and G.widescreen and 0.35 or 0)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
G.jokers.T.y = 0
'''
position = "at"
payload = '''
G.jokers.T.y = 0 + ((SilkTouch.OS == 'Android' or SilkTouch.OS == 'iOS') and G.widescreen and -0.2 or 0)
G.jokers.T.w = G.jokers.T.w + ((SilkTouch.OS == 'Android' or SilkTouch.OS == 'iOS') and G.widescreen and 0.4 or 0)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
G.consumeables.T.x = G.jokers.T.x + G.jokers.T.w + 0.2
G.consumeables.T.y = 0
'''
position = "at"
payload = '''
G.consumeables.T.x = G.jokers.T.x + G.jokers.T.w + 0.2 + ((SilkTouch.OS == 'Android' or SilkTouch.OS == 'iOS') and G.widescreen and 0.8 or 0)
G.consumeables.T.y = 0 + ((SilkTouch.OS == 'Android' or SilkTouch.OS == 'iOS') and G.widescreen and -0.2 or 0)
G.consumeables.T.w = G.consumeables.T.w + ((SilkTouch.OS == 'Android' or SilkTouch.OS == 'iOS') and G.widescreen and 0.2 or 0)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
G.deck.T.x = G.TILE_W - G.deck.T.w - 0.5
'''
position = "at"
payload = '''
G.deck.T.x = G.TILE_W - G.deck.T.w - 0.5 + ((SilkTouch.OS == 'Android' or SilkTouch.OS == 'iOS') and G.widescreen and 0.8 or 0)
'''
match_indent = true