[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = '''
self.collision_list = {} --A list of all node that the cursor currently collides with
'''
position = "after"
payload = '''
--Touch controller
self.touch_control = {s_tap = {target = nil,handled = true}, l_press = {target = nil, handled = true}}
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = '''
self.cursor_hover.time = G.TIMERS.TOTAL
'''
position = "after"
payload = '''
self.cursor_hover.uptime = G.TIMERS.UPTIME
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = '''
self:L_cursor_press(self.L_cursor_queue.x, self.L_cursor_queue.y)
'''
position = "after"
payload = '''
self.cursor_down.uptime = G.TIMERS.UPTIME
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = '''
self.cursor_up.time = G.TIMERS.TOTAL
'''
position = "after"
payload = '''
self.cursor_up.uptime = G.TIMERS.UPTIME
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = '''
if not self.cursor_down.handled then
'''
position = "after"
payload = '''
    if self.HID.touch then
        if self.cursor_hover.target and self.cursor_hover.target.states.hover.can then
            self.finger_focus = self.cursor_hover.target
        end
        self.touch_control.clear_touch = true
    end
    self.cursor_down.distance = 0
    self.cursor_down.duration = 0
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = '''
--The object being dragged
'''
position = "before"
payload = '''
if self.HID.touch then
    if self.finger_focus and not self.finger_focus:can_long_press() then
        if self.finger_focus ~= self.hovering.target and self.finger_focus:can_hover_on_drag() then
            self.hovering.target = self.finger_focus
            self.hovering.handled = false
        end
    end

    if not self.touch_control.l_press.handled then
        self.hovering.target = self.touch_control.l_press.target
        self.hovering.handled = false
        self.touch_control.l_pressed = self.finger_focus
        self.touch_control.l_press.handled = true
    end

    if self.touch_control.clear_touch or not self.finger_focus then
        self.touch_control.l_press.target = nil
        self.touch_control.l_pressed = nil
        self.touch_control.s_tap.target = nil
        self.hovering.target = nil

        self.hovering.handled = false
        self.touch_control.clear_touch = nil
    end

    if self.touch_control.l_pressed then
        self.hovering.target = self.finger_focus
    end
end
if not self.dragging.handled and self.cursor_down.duration and (self.cursor_down.duration > 0.1) then
    create_drag_target_from_card(self.dragging.target)
    self.dragging.handled = true
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = '''
if self.hovering.target and self.hovering.target == self.dragging.target and not self.HID.touch then
    self.hovering.target:stop_hover()
end
'''
position = "after"
payload = '''
if self.is_cursor_down then 
    self.cursor_down.distance = math.max(Vector_Dist(self.cursor_down.T, self.cursor_hover.T), self.cursor_down.distance or 0)
    self.cursor_down.duration = G.TIMERS.UPTIME - (self.cursor_down.uptime or 0)
    if self.cursor_up.target then
        self.cursor_up.target = nil
    end
end
if not self.is_cursor_down then
    if self.cursor_down.target then
        self.cursor_down.target = nil
        self.cursor_down.distance = nil
        self.cursor_down.duration = nil
    end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = '''
self.hovering.target.states.hover.is = false
self.hovering.target = nil
'''
position = "at"
payload = '''
if self.HID.touch and not self.hovering.target:can_long_press() then
else
    self.hovering.target.states.hover.is = false
    self.hovering.target = nil
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = '''
--Cursor is currently hovering over something
'''
position = "before"
payload = '''
if self.HID.touch then
    if self.finger_focus then
        if self.is_cursor_down and self.finger_focus:can_long_press() and self.cursor_down.duration > (0.2 * G.SPEEDFACTOR) and not self.touch_control.l_press.target and not self.touch_control.l_pressed then
            self.touch_control.l_press.target = self.finger_focus
            self.touch_control.l_press.handled = false
        end
    end
end
'''
match_indent = true
