[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
config = {align=('cli'), offset = {x=-0.7,y=0},major = G.ROOM_ATTACH}
'''
position = "at"
payload = '''
config = {align=('cli'), offset = {x=-0.7+((SilkTouch.OS == 'Android' or SilkTouch.OS == 'iOS') and G.widescreen and -0.9 or 0),y=0},major = G.ROOM_ATTACH}
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
config = {align="bm", offset = {x=0,y=0.3},major = G.hand, bond = 'Weak'}
'''
position = "at"
payload = '''
config = {align="bm", offset = {x=0+((SilkTouch.OS == 'Android' or SilkTouch.OS == 'iOS') and G.widescreen and -0.1 or 0),y=0.3},major = G.hand, bond = 'Weak'}
'''
match_indent = true