[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.regex]
target = "engine/sprite.lua"
pattern = '''\(_draw_major\.hover_tilt or 0\)\*\(tilt_shadow or 1\)'''
position = "at"
payload = "((not G.CONTROLLER.HID.touch or G.SETTINGS.drag_option == 2) and _draw_major.hover_tilt or 0)*(tilt_shadow or 1)"