[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
function G.UIDEF.card_focus_ui(card)
'''
position = "before"
payload = '''
-- Function overridden by SilkTouch in src/util.lua
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
function G.UIDEF.card_focus_button(args)
'''
position = "before"
payload = '''
-- Function overridden by SilkTouch in src/util.lua
'''
match_indent = true

[[patches]]
[patches.regex]
target = "functions/UI_definitions.lua"
pattern = '''0\.6\*args\.scale'''
position = "at"
payload = '''0.6*args.scale*((SilkTouch.OS == 'Android' or SilkTouch.OS == 'iOS') and 2 or 1)'''

[[patches]]
[patches.regex]
target = "functions/UI_definitions.lua"
pattern = '''minh = 0\.6, minw = 2\.7,'''
position = "at"
payload = '''minh = 0.6*((SilkTouch.OS == 'Android' or SilkTouch.OS == 'iOS') and not run_info and 2 or 1), minw = 2.7,'''

[[patches]]
[patches.regex]
target = "functions/UI_definitions.lua"
pattern = '''minh = 0\.7, minw = 0\.9,'''
position = "at"
payload = '''minh = 0.7, minw = 0.9*((SilkTouch.OS == 'Android' or SilkTouch.OS == 'iOS') and 1.5 or 1),'''

[[patches]]
[patches.regex]
target = "functions/UI_definitions.lua"
pattern = '''scale = target\.scale'''
position = "at"
payload = '''ignore_mobile_ui = true, scale = target.scale'''

[[patches]]
[patches.regex]
target = "functions/UI_definitions.lua"
pattern = '''ref_value = type, scale = 0\.45'''
position = "at"
payload = '''ref_value = type, scale = 0.45*((SilkTouch.OS == 'Android' or SilkTouch.OS == 'iOS') and 1.5 or 1)'''

[[patches]]
[patches.regex]
target = "functions/UI_definitions.lua"
pattern = '''id = args\.back_id or 'overlay_menu_back_button', align = "cm", minw = 2\.5,'''
position = "at"
payload = '''id = args.back_id or 'overlay_menu_back_button', align = "cm", minw = 2.5, minh = 0.6*((SilkTouch.OS == 'Android' or SilkTouch.OS == 'iOS') and 1.5 or 1),'''

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
offset = G.HUD_tags[1] and {x=0,y=0} or {x=0.7,y=0},
'''
position = "at"
payload = '''
offset = G.HUD_tags[1] and {x=0,y=0} or {x=0.7+((SilkTouch.OS == 'Android' or SilkTouch.OS == 'iOS') and G.widescreen and 0.8 or 0),y=0},
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
G.F_RUMBLE and create_toggle({label = localize('b_set_rumble'), ref_table = G.SETTINGS, ref_value = 'rumble'}) or nil,
'''
position = "at"
payload = '''
G.F_RUMBLE and create_toggle({label = localize('b_set_rumble'), ref_table = G.SETTINGS, ref_value = 'rumble'})
or (SilkTouch.OS == 'Android' or SilkTouch.OS == 'iOS')
and create_toggle({label = localize('b_vibration'), ref_table = G.SETTINGS, ref_value = 'vibration'}) or nil,
'''
match_indent = true